/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_sound_AudioManager */

#ifndef _Included_com_wiyun_engine_sound_AudioManager
#define _Included_com_wiyun_engine_sound_AudioManager
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wiyun_engine_sound_AudioManager_FORMAT_MP3
#define com_wiyun_engine_sound_AudioManager_FORMAT_MP3 1L
#undef com_wiyun_engine_sound_AudioManager_FORMAT_WAV
#define com_wiyun_engine_sound_AudioManager_FORMAT_WAV 2L
/*
 * Class:     com_wiyun_engine_sound_AudioManager
 * Method:    nativeSetConfig
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_sound_AudioManager_nativeSetConfig
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_wiyun_engine_sound_AudioManager
 * Method:    nativePlayBackgroundMusic
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_sound_AudioManager_nativePlayBackgroundMusic__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_wiyun_engine_sound_AudioManager
 * Method:    nativePlayBackgroundMusic
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_sound_AudioManager_nativePlayBackgroundMusic__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_wiyun_engine_sound_AudioManager
 * Method:    nativePlayBackgroundMusic
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_sound_AudioManager_nativePlayBackgroundMusic__Ljava_lang_String_2I
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_wiyun_engine_sound_AudioManager
 * Method:    nativePlayEffect
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_sound_AudioManager_nativePlayEffect__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_wiyun_engine_sound_AudioManager
 * Method:    nativePlayEffect
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_sound_AudioManager_nativePlayEffect__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_wiyun_engine_sound_AudioManager
 * Method:    nativePlayEffect
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_sound_AudioManager_nativePlayEffect__Ljava_lang_String_2I
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_wiyun_engine_sound_AudioManager
 * Method:    nativeStopBackgroundMusic
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_sound_AudioManager_nativeStopBackgroundMusic
  (JNIEnv *, jclass);

/*
 * Class:     com_wiyun_engine_sound_AudioManager
 * Method:    nativeResumeBackgroundMusic
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_sound_AudioManager_nativeResumeBackgroundMusic
  (JNIEnv *, jclass);

/*
 * Class:     com_wiyun_engine_sound_AudioManager
 * Method:    nativePauseBackgroundMusic
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_sound_AudioManager_nativePauseBackgroundMusic
  (JNIEnv *, jclass);

/*
 * Class:     com_wiyun_engine_sound_AudioManager
 * Method:    nativePreloadEffect
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_sound_AudioManager_nativePreloadEffect__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_wiyun_engine_sound_AudioManager
 * Method:    nativePreloadEffect
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_sound_AudioManager_nativePreloadEffect__ILjava_lang_String_2
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_wiyun_engine_sound_AudioManager
 * Method:    nativePlayPreloadEffect
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_sound_AudioManager_nativePlayPreloadEffect
  (JNIEnv *, jclass, jint, jint);


#ifdef __cplusplus
}
#endif
#endif
