/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_opengl_Texture2D */

#ifndef _Included_com_wiyun_engine_opengl_Texture2D
#define _Included_com_wiyun_engine_opengl_Texture2D
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wiyun_engine_opengl_Texture2D_SOURCE_JPG
#define com_wiyun_engine_opengl_Texture2D_SOURCE_JPG 1L
#undef com_wiyun_engine_opengl_Texture2D_SOURCE_PNG
#define com_wiyun_engine_opengl_Texture2D_SOURCE_PNG 2L
#undef com_wiyun_engine_opengl_Texture2D_SOURCE_PVR
#define com_wiyun_engine_opengl_Texture2D_SOURCE_PVR 3L
#undef com_wiyun_engine_opengl_Texture2D_SOURCE_LABEL
#define com_wiyun_engine_opengl_Texture2D_SOURCE_LABEL 4L
#undef com_wiyun_engine_opengl_Texture2D_SOURCE_BITMAP
#define com_wiyun_engine_opengl_Texture2D_SOURCE_BITMAP 5L
#undef com_wiyun_engine_opengl_Texture2D_SOURCE_OPENGL
#define com_wiyun_engine_opengl_Texture2D_SOURCE_OPENGL 6L
/*
 * Class:     com_wiyun_engine_opengl_Texture2D
 * Method:    nativeNew
 * Signature: (IIF)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_opengl_Texture2D_nativeNew__IIF
  (JNIEnv *, jobject, jint, jint, jfloat);

/*
 * Class:     com_wiyun_engine_opengl_Texture2D
 * Method:    nativeNew
 * Signature: (ILjava/lang/String;F)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_opengl_Texture2D_nativeNew__ILjava_lang_String_2F
  (JNIEnv *, jobject, jint, jstring, jfloat);

/*
 * Class:     com_wiyun_engine_opengl_Texture2D
 * Method:    nativeNew
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_opengl_Texture2D_nativeNew__III
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_wiyun_engine_opengl_Texture2D
 * Method:    nativeNew
 * Signature: (Ljava/lang/String;FLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_opengl_Texture2D_nativeNew__Ljava_lang_String_2FLjava_lang_String_2
  (JNIEnv *, jobject, jstring, jfloat, jstring);

/*
 * Class:     com_wiyun_engine_opengl_Texture2D
 * Method:    nativeNew
 * Signature: (Ljava/lang/String;FLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_opengl_Texture2D_nativeNew__Ljava_lang_String_2FLjava_lang_String_2I
  (JNIEnv *, jobject, jstring, jfloat, jstring, jint);

/*
 * Class:     com_wiyun_engine_opengl_Texture2D
 * Method:    nativeNew
 * Signature: (Landroid/graphics/Bitmap;)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_opengl_Texture2D_nativeNew__Landroid_graphics_Bitmap_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wiyun_engine_opengl_Texture2D
 * Method:    nativeNewFile
 * Signature: (ILjava/lang/String;F)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_opengl_Texture2D_nativeNewFile
  (JNIEnv *, jobject, jint, jstring, jfloat);

/*
 * Class:     com_wiyun_engine_opengl_Texture2D
 * Method:    setAntiAlias
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_opengl_Texture2D_setAntiAlias
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_opengl_Texture2D
 * Method:    setRepeat
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_opengl_Texture2D_setRepeat
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wiyun_engine_opengl_Texture2D
 * Method:    setTexParameters
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_opengl_Texture2D_setTexParameters
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_wiyun_engine_opengl_Texture2D
 * Method:    applyTexParameters
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_opengl_Texture2D_applyTexParameters
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_opengl_Texture2D
 * Method:    nativeDrawAtPoint
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_opengl_Texture2D_nativeDrawAtPoint__FF
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_wiyun_engine_opengl_Texture2D
 * Method:    nativeDrawAtPoint
 * Signature: (FFZZ)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_opengl_Texture2D_nativeDrawAtPoint__FFZZ
  (JNIEnv *, jobject, jfloat, jfloat, jboolean, jboolean);

/*
 * Class:     com_wiyun_engine_opengl_Texture2D
 * Method:    getHeight
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_opengl_Texture2D_getHeight
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_opengl_Texture2D
 * Method:    getWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_opengl_Texture2D_getWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_opengl_Texture2D
 * Method:    loadTexture
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_opengl_Texture2D_loadTexture
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_opengl_Texture2D
 * Method:    glDelete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_opengl_Texture2D_glDelete
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_opengl_Texture2D
 * Method:    getWidthScale
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_opengl_Texture2D_getWidthScale
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_opengl_Texture2D
 * Method:    getHeightScale
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_wiyun_engine_opengl_Texture2D_getHeightScale
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_opengl_Texture2D
 * Method:    getName
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_opengl_Texture2D_getName
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_opengl_Texture2D
 * Method:    setName
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_opengl_Texture2D_setName
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wiyun_engine_opengl_Texture2D
 * Method:    getPixelHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_opengl_Texture2D_getPixelHeight
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_opengl_Texture2D
 * Method:    getPixelWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_opengl_Texture2D_getPixelWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_wiyun_engine_opengl_Texture2D
 * Method:    getTexId
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wiyun_engine_opengl_Texture2D_getTexId
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
