/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_sound_AudioEngine */

#ifndef _Included_com_wiyun_engine_sound_AudioEngine
#define _Included_com_wiyun_engine_sound_AudioEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_sound_AudioEngine
 * Method:    nativeReadMixAudio
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_wiyun_engine_sound_AudioEngine_nativeReadMixAudio
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_wiyun_engine_sound_AudioEngine
 * Method:    nativeRequireRepeat
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wiyun_engine_sound_AudioEngine_nativeRequireRepeat
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
